apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline
  template:
    metadata:
      labels:
        app: aline
    spec:
      containers:
      - name: user-app
        image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/user-microservice
        env:
        - name: APP_PORT
          value: '8070'
        - name: DB_USERNAME
          valueFrom:
           secretKeyRef:
             name: secret
             key: username
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: secret
             key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: ENCRYPT_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET_KEY
        ports:
        - name: user
          containerPort: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-deployment
  labels:
    app: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline
  template:
    metadata:
      labels:
        app: aline
    spec:
      containers:
      - name: underwriter-app
        image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/underwriter-microservice
        env:
        - name: APP_PORT
          value: '8071'
        - name: DB_USERNAME
          valueFrom:
           secretKeyRef:
             name: secret
             key: username
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: secret
             key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: ENCRYPT_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET_KEY
        ports:
        - name: underwriter
          containerPort: 8071
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  labels:
    app: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline
  template:
    metadata:
      labels:
        app: aline
    spec:
      containers:
      - name: bank-app
        image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/bank-microservice
        env:
        - name: APP_PORT
          value: '8083'
        - name: DB_USERNAME
          valueFrom:
           secretKeyRef:
             name: secret
             key: username
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: secret
             key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: ENCRYPT_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET_KEY
        ports:
        - name: bank
          containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline
  template:
    metadata:
      labels:
        app: aline
    spec:
      containers:
      - name: transaction-app
        image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/transaction-microservice
        env:
        - name: APP_PORT
          value: '8073'
        - name: DB_USERNAME
          valueFrom:
           secretKeyRef:
             name: secret
             key: username
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: secret
             key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: ENCRYPT_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET_KEY
        ports:
        - name: transaction
          containerPort: 8073
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline
  template:
    metadata:
      labels:
        app: aline
    spec:
      containers:
      - name: gateway
        image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/gateway
        env:
        - name: APP_PORT
          value: '8080'
        - name: APP_SERVICE_HOST
          value: aline-backend-service
        - name: DB_USERNAME
          valueFrom:
           secretKeyRef:
             name: secret
             key: username
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: secret
             key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: ENCRYPT_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: JWT_SECRET_KEY
        ports:
        - name: gateway
          containerPort: 8080
      nodeSelector:
        nodeGroup: "public_node_group"