apiVersion: v1
kind: Service
metadata:
  name: aline-backend-service
  namespace: eks-js
spec:
  type: ClusterIP
  selector:
    app: aline
  ports:
  - name: user-port
    port: 8070
    targetPort: user
  - name: underwriter-port
    port: 8071
    targetPort: underwriter
  - name: transaction-port
    port: 8073
    targetPort: transaction
  - name: bank-port
    port: 8083
    targetPort: bank
---
apiVersion: v1
kind: Service
metadata:
  name: aline-gateway-service
  namespace: eks-js
spec:
  type: NodePort
  selector:
    app: aline
  ports:
  - name: gateway-port
    port: 8080
    targetPort: 8080
    nodePort: 30000