apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: eks-js
type: Opaque
data:
  username: YWRtaW4=
  password: cHJhbW9kY2hhbmRyYWthcnRoaWNrYWtiYXIxIQ==
  ENCRYPT_SECRET_KEY: LU4gTlZOQ1dxNEtFREhYTmpzYXpkR1gyMFoxCg==
  JWT_SECRET_KEY: LU4gMXdIcVFGZFVsVXI1VFpOcjF3VENpdXlNMFZ5ZTJMNGpYCg==
