apiVersion: v1
kind: Service
metadata:
  name: aline-backend-service
spec:
  type: NodePort
  selector:
    app: aline
  ports:
  - name: user-port
    port: 8070
    targetPort: user
    nodePort: 30070
  - name: underwriter-port
    port: 8071
    targetPort: underwriter
    nodePort: 30071
  - name: transaction-port
    port: 8073
    targetPort: transaction
    nodePort: 30073
  - name: bank-port
    port: 8083
    targetPort: bank
    nodePort: 30083