apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  username: cm9vdA==
  password: UGFzc3dvcmQxIQ==
  ENCRYPT_SECRET_KEY: LU4gTlZOQ1dxNEtFREhYTmpzYXpkR1gyMFoxCg==
  JWT_SECRET_KEY: LU4gMXdIcVFGZFVsVXI1VFpOcjF3VENpdXlNMFZ5ZTJMNGpYCg==
