services:
  database:
    image: jsherer/aline-db:0.9
    ports:
      - "3307:3306"
    env_file:
      - ./backend.env
  user:
    image: jsherer/aline-user-microservice:1.0
    restart: on-failure:6
    depends_on:
      - database
    ports:
      - "8070:8070"
    env_file:
      - ./backend.env
  bank:
    image: jsherer/aline-bank-microservice:1.0
    restart: on-failure:6
    depends_on:
      - database
    ports:
      - "8083:8083"
    env_file:
      - ./backend.env
  underwriter:
    image: jsherer/aline-underwriter-microservice:1.0
    restart: on-failure:6
    depends_on:
      - database
    ports:
      - "8071:8071"
    env_file:
      - ./backend.env
  transaction:
    image: jsherer/aline-transaction-microservice:1.0
    restart: on-failure:6
    depends_on:
      - database
    ports:
      - "8073:8073"
    env_file:
      - ./backend.env
